In [1]:
import tensorflow as tf
import numpy as np

In [2]:
#스칼라 정의
a = tf.constant(1)
b = tf.constant(2)
print(a)
print(b)
print(tf.rank(a)) #차원 확인
a = tf.cast(a,tf.float32)
b = tf.cast(b,tf.float32)
print(a)
print(b)
#계산 : add(덧셈), subtract(뺄셈), multiply(곱셈), divide(나눗셈), mod(나눗셈_나머지), floordiv(나눗셈_몫),square(거듭제곱),sqrt(제곱근),
c = tf.math.add(a,b)
d = tf.math.square(c)
print(c)
print(tf.rank(c)) #차원 확인
print(d)
print(tf.rank(d)) #차원 확인

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(0, shape=(), dtype=int32)


In [3]:
#1차원 배열 정의
py_list = [10., 20., 30.] #파이썬 리스트
num_arr = np.array([10.,10.,10.]) #넘파이 배열

#텐서 변환(벡터)
vec1 = tf.constant(py_list, dtype = tf.float32)
vec2 = tf.constant(num_arr, dtype = tf.float32)

print(vec1)
print(vec2)
print(tf.rank(vec1))
print(tf.rank(vec2))

add1 = tf.math.add(vec1,vec2) #다른 연산 함수도 전부 사용 가능
print(add1)
print(tf.rank(add1))

add2 = vec1 + vec2 #다른 연산자도 전부 사용 가능
print(add2)
print(tf.rank(add2))

print(tf.reduce_sum(vec1)) #벡터를 구성하는 모든 원소들의 합 계산
print(tf.reduce_sum(vec2)) #벡터를 구성하는 모든 원소들의 합 계산

print(vec1 + 1) #브로드캐스팅 연산


tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(60.0, shape=(), dtype=float32)
tf.Tensor(30.0, shape=(), dtype=float32)
tf.Tensor([11. 21. 31.], shape=(3,), dtype=float32)


In [4]:
#2차원 배열 정의
list_of_list = [[10,20],[30,40]]

#텐서 변환(메트릭스)
mat1 = tf.constant(list_of_list)

print(mat1)
print(tf.rank(mat1))

#벡터 정의
vec1 = tf.constant([1, 0])
vec2 = tf.constant([-1, 2])

#텐서 변환(메트릭스)_stack
mat2 = tf.stack([vec1,vec2])

print(mat2)
print(tf.rank(mat2))

#연산
element_mul = tf.math.multiply(mat1,mat2)
print(element_mul)
print(tf.rank(element_mul))

#연산_브로드 캐스팅
element_bc = tf.math.multiply(mat1,3)
print(element_bc)
print(tf.rank(element_bc))

#행렬곱 연산(선형대수)
mat_mul = tf.matmul(mat1,mat2)
print(mat_mul)
print(tf.rank(mat_mul))

#넘파이 배열로 변환
np_arr = mat_mul.numpy()
print(type(np_arr))
print(np_arr)

tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[ 1  0]
 [-1  2]], shape=(2, 2), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[ 10   0]
 [-30  80]], shape=(2, 2), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[ 30  60]
 [ 90 120]], shape=(2, 2), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[-10  40]
 [-10  80]], shape=(2, 2), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
<class 'numpy.ndarray'>
[[-10  40]
 [-10  80]]


In [12]:
#고차원 텐서

#2차원 배열 정의
mat1 = [[1,2,3,4],[5,6,7,8]]
mat2 = [[9,10,11,12],[12,13,14,15]]
mat3 = [[16,17,18,20],[21,22,23,24]]

#텐서 변환(3차원 텐서)
tensor1 = tf.constant([mat1,mat2,mat3])

#랭크 확인
print(tensor1)
print(tf.rank(tensor1))

#텐서 변환(3차원 텐서)_stack
tensor2 = tf.stack([mat1,mat2,mat3])

#랭크 확인
print(tensor2)
print(tf.rank(tensor2))

vec1 = [1,2,3,4]
vec2 = [5,6,7,8]
vec3 = [9,10,11,12]
vec4 = [12,13,14,15]
vec5 = [16,17,18,20]
vec6 = [21,22,23,24]

arr = [[vec1,vec2],
       [vec3,vec4],
       [vec5,vec6]]

tensor3 = tf.constant(arr)

print(tensor3)
print(tf.rank(tensor3))

#랭크-4 텐서
tensor4 = tf.stack([tensor1,tensor2,tensor3])
print(tensor4)
print(tf.rank(tensor4))

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [12 13 14 15]]

 [[16 17 18 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [12 13 14 15]]

 [[16 17 18 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [12 13 14 15]]

 [[16 17 18 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [12 13 14 15]]

  [[16 17 18 20]
   [21 22 23 24]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [12 13 14 15]]

  [[16 17 18 20]
   [21 22 23 24]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [12 13 14 15]]

  [[16 17 18 20]
   [21 22 23 24]]]], shape=(3, 3, 2, 4), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [13]:
#Tensor의 인덱싱
vec = tf.constant([10,20,30,40,50])
print(vec)
print(vec[0])
print(vec[-1])
print(vec[:3])

mat = tf.constant([[1,2,3,4],[5,6,7,8]])
print(mat[0,2])
print(mat[0,:])
print(mat[:,1])
print(mat[:,:])



mat1 = [[1,2,3,4],[5,6,7,8]]
mat2 = [[9,10,11,12],[12,13,14,15]]
mat3 = [[16,17,18,20],[21,22,23,24]]
tensor = tf.constant([mat1,mat2,mat3])
print(tensor)
print(tensor[0,:,:])
print(tensor[:,:2,:2])


tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([2 6], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [12 13 14 15]]

 [[16 17 18 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[[ 1  2]
  [ 5  6]]

 [[ 9 10]
  [12 13]]

 [[16 17]
  [21 22]]], shape=(3, 2, 2), dtype=int32)


In [28]:
#Tensor의 형태 변환
tensor = tf.constant(range(0,24))
print(tensor)
#→형태변환 실시
tensor1 = tf.reshape(tensor, [-1,2,2,]) #-1을 넣는다는건 어떠한 수라도 상관이 없다는 뜻
print(tensor1)

tensor2 = tf.reshape(tensor1, [3,-1,2,]) #-1을 넣는다는건 어떠한 수라도 상관이 없다는 뜻
print(tensor2)

tensor3 = tf.reshape(tensor2, [2,3,-1,2,]) #-1을 넣는다는건 어떠한 수라도 상관이 없다는 뜻
print(tensor3)

tensor4 = tf.reshape(tensor3,[-1]) #다시 벡터 형태로 변경
print(tensor4)


tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)
tf.Tensor(
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]], shape=(6, 2, 2), dtype=int32)
tf.Tensor(
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]], shape=(3, 4, 2), dtype=int32)
tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]], shape=(2, 3, 2, 2), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [42]:
#변수
tensor1 = tf.constant([[0,1,2],[3,4,5]]) #메트릭스 선언
print(tensor1)

tensor_var1 = tf.Variable(tensor1) #변수 할당
print(tensor_var1)

print("이름 :",tensor_var1.name)
print("크기 :",tensor_var1.shape)
print("자료형 :",tensor_var1.dtype)
print("배열 :",tensor_var1.numpy())

tensor_var1.assign([[1,1,1],[2,2,2]]) #변수 재할당
print(tensor_var1)

tensor2 = tf.convert_to_tensor(tensor_var1) #변수를 텐서로 변환
print(tensor2)

tensor_var2 = tf.Variable(tensor2, name='New Name') #변수에 이름 할당
print(tensor_var2)

tensor_var1 + tensor_var2 #변수끼리 합산(단 출력물은 각 변수가 가지고 있는 텐서의 합으로 나타내므로 변수형태가 아닌 텐서로 나옴)


tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>
이름 : Variable:0
크기 : (2, 3)
자료형 : <dtype: 'int32'>
배열 : [[0 1 2]
 [3 4 5]]
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]])>
tf.Tensor(
[[1 1 1]
 [2 2 2]], shape=(2, 3), dtype=int32)
<tf.Variable 'New Name:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]])>


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [4, 4, 4]])>

In [4]:
#자동미분
g = tf.random.Generator.from_seed(2020)
x = g.normal(shape = (10,))
y = 3*x-2

print('x :',x.numpy())
print('y :',y.numpy())

#손실 함수 정의
def cal_mse(x,y,a,b):
    y_pred = a*x+b
    squared_error = (y_pred - y)**2
    mean_squared_error = tf.reduce_mean(squared_error)
    return mean_squared_error


a = tf.Variable(0.0)
b = tf.Variable(0.0)

EPOCHS = 200

for epoch in range(1, EPOCHS + 1):
    with tf.GradientTape() as tape:
        mse = cal_mse(x,y,a,b)
    grad = tape.gradient(mse,{'a':a,'b':b})
    d_a,d_b = grad['a'],grad['b']
    
    a.assign_sub(d_a*0.05)
    b.assign_sub(d_b*0.05)
    
    if epoch%20 == 0:
        print('EPOCH %d - MSE : %.4f ----- a : %.2f ------ b : %.2f'%(epoch, mse, a, b))
    





x : [-0.20943771  1.2746525   1.213214   -0.17576952  1.876984    0.16379918
  1.082245    0.6199966  -0.44402212  1.3048344 ]
y : [-2.628313    1.8239574   1.6396422  -2.5273085   3.630952   -1.5086024
  1.2467351  -0.14001012 -3.3320663   1.9145031 ]
tf.Tensor(5.11122, shape=(), dtype=float32)
1
2
tf.Tensor(4.555297, shape=(), dtype=float32)
1
2
tf.Tensor(4.102832, shape=(), dtype=float32)
1
2
tf.Tensor(3.7264862, shape=(), dtype=float32)
1
2
tf.Tensor(3.4070325, shape=(), dtype=float32)
1
2
tf.Tensor(3.1308815, shape=(), dtype=float32)
1
2
tf.Tensor(2.8883655, shape=(), dtype=float32)
1
2
tf.Tensor(2.6725478, shape=(), dtype=float32)
1
2
tf.Tensor(2.478399, shape=(), dtype=float32)
1
2
tf.Tensor(2.3022268, shape=(), dtype=float32)
1
2
tf.Tensor(2.141275, shape=(), dtype=float32)
1
2
tf.Tensor(1.9934533, shape=(), dtype=float32)
1
2
tf.Tensor(1.8571408, shape=(), dtype=float32)
1
2
tf.Tensor(1.7310549, shape=(), dtype=float32)
1
2
tf.Tensor(1.6141573, shape=(), dtype=float32)
1
2
tf.

In [7]:
#자동미분
g = tf.random.Generator.from_seed(2020)
x = g.normal(shape = (10,))
y = 3*x-2

print('x :',x.numpy())
print('y :',y.numpy())

#손실 함수 정의
def cal_mse(x,y,a,b):
    y_pred = a*x+b
    squared_error = (y_pred - y)**2
    mean_squared_error = tf.reduce_mean(squared_error)
    return mean_squared_error


a = tf.Variable(0.0)
b = tf.Variable(0.0)

EPOCHS = 200

for epoch in range(1, EPOCHS + 1):
    with tf.GradientTape() as tape:
        mse = cal_mse(x,y,a,b)
    grad = tape.gradient(mse,{'a':a,'b':b})
    d_a,d_b = grad['a'],grad['b']
    print('1    EPOCH %d - MSE : %.4f ----- a : %.2f ------ b : %.2f'%(epoch, mse, a, b))
    
    a.assign_sub(d_a*0.05)
    b.assign_sub(d_b*0.05)

    print('2    EPOCH %d - MSE : %.4f ----- a : %.2f ------ b : %.2f'%(epoch, mse, a, b))

x : [-0.20943771  1.2746525   1.213214   -0.17576952  1.876984    0.16379918
  1.082245    0.6199966  -0.44402212  1.3048344 ]
y : [-2.628313    1.8239574   1.6396422  -2.5273085   3.630952   -1.5086024
  1.2467351  -0.14001012 -3.3320663   1.9145031 ]
1    EPOCH 1 - MSE : 5.1112 ----- a : 0.00 ------ b : 0.00
2    EPOCH 1 - MSE : 5.1112 ----- a : 0.17 ------ b : 0.00
1    EPOCH 2 - MSE : 4.5553 ----- a : 0.17 ------ b : 0.00
2    EPOCH 2 - MSE : 4.5553 ----- a : 0.32 ------ b : -0.01
1    EPOCH 3 - MSE : 4.1028 ----- a : 0.32 ------ b : -0.01
2    EPOCH 3 - MSE : 4.1028 ----- a : 0.46 ------ b : -0.03
1    EPOCH 4 - MSE : 3.7265 ----- a : 0.46 ------ b : -0.03
2    EPOCH 4 - MSE : 3.7265 ----- a : 0.59 ------ b : -0.06
1    EPOCH 5 - MSE : 3.4070 ----- a : 0.59 ------ b : -0.06
2    EPOCH 5 - MSE : 3.4070 ----- a : 0.70 ------ b : -0.09
1    EPOCH 6 - MSE : 3.1309 ----- a : 0.70 ------ b : -0.09
2    EPOCH 6 - MSE : 3.1309 ----- a : 0.81 ------ b : -0.13
1    EPOCH 7 - MSE : 2.8884 --